---
root: true
env:
  es2021: true
  node: true
  browser: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project: tsconfig(.*)?.json
  createDefaultProgram: true
  ignorePatterns:
    - '**/*'
    - 'dist/**/*'
    - 'node_modules/**/*'
plugins:
  - '@nrwl/nx'
  - '@typescript-eslint'
  - eslint-comments
  - 'no-loops'
extends:
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:eslint-comments/recommended
  - plugin:prettier/recommended
  - plugin:node/recommended
overrides:
  - files:
      - '*.ts'
      - '*.tsx'
      - '*.js'
      - '*.jsx'
    rules:
      '@nrwl/nx/enforce-module-boundaries':
        - error
        - enforceBuildableLibDependency: true
          allow: []
          depConstraints:
            - sourceTag: '*'
              onlyDependOnLibsWithTags:
                - '*'
      # core
      node/no-missing-import: off
      node/no-unsupported-features/es-syntax:
        - error
        - version: '>=16.13.1'
          ignores:
            - modules
      no-console: 0
      consistent-return: 0
      quotes:
        - error
        - single
        - avoidEscape: true
          allowTemplateLiterals: true

      # variables
      no-unused-vars: 0

      # style
      object-curly-newline: 0
      lines-between-class-members: 0
      implicit-arrow-linebreak: 0
      arrow-body-style:
        - error
        - as-needed

      # import
      import/extensions: off
      import/named: off
      import/default: off
      import/namespace: off
      import/no-unresolved: off
      import/group-exports: off
      import/no-named-export: off
      import/no-named-as-default: off
      import/no-named-as-default-member: off

      import/first: error
      import/no-amd: error
      import/no-duplicates: error
      import/no-self-import: error
      import/no-absolute-path: error
      import/no-named-default: error
      import/no-mutable-exports: error
      import/newline-after-import: error
      import/order:
        - error
        - groups:
            - builtin
            - external
            - internal
          newlines-between: never
          alphabetize:
            order: asc
            caseInsensitive: false

      # no-loops
      no-loops/no-loops: 2

      # comments
      eslint-comments/disable-enable-pair: off
  - files:
      - '*.ts'
      - '*.tsx'
    extends:
      - plugin:@nrwl/nx/typescript
    rules:
      # typescript
      '@typescript-eslint/lines-between-class-members': off
  - files:
      - '*.js'
      - '*.jsx'
    extends:
      - plugin:@nrwl/nx/javascript
    rules: {}
