ci:
  collect:
    settings:
      disableStorageReset: true
      maxWaitForLoad: 90000
      throttlingMethod: devtools
      additive: false
  assert:
    present: lighthouse:recommended
    assertions:
      categories:performance:
        - error
        - minScore: 0.9
      categories:accessibility:
        - error
        - minScore: 1
      categories:best-practices:
        - error
        - minScore: 1
      categories:seo:
        - error
        - minScore: 1
      categories:pwa:
        - error
        - minScore: 1
  upload:
    target: temporary-public-storage
