name: Semantic Release
description: Release a new version
inputs:
  token:
    description: Github Repository Token
    required: true
  version:
    description: Semantic Version
    required: true
runs:
  using: composite
  steps:
    - uses: cycjimmy/semantic-release-action@v3
      id: semantic
      with:
        semantic_version: ${{ inputs.version }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
    - if: steps.semantic.outputs.new_release_published == 'true'
      shell: bash
      run: |
        echo ${{ steps.semantic.outputs.new_release_version }}
        echo ${{ steps.semantic.outputs.new_release_major_version }}
        echo ${{ steps.semantic.outputs.new_release_minor_version }}
        echo ${{ steps.semantic.outputs.new_release_patch_version }}
