name: Setup NodeJS
description: Setup NodeJS
inputs:
  version:
    description: Node version
    required: false
    default: '16'
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.version }}
