name: Deployment

concurrency:
  group: production
  cancel-in-progress: true

on:
  release:
    types:
      - created

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npx nx run front:build:production
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: firebase
        with:
          channelId: live
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID_PRODUCTION }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NX_MONO }}
      - run: npx lhci autorun --collect.url=${{ steps.firebase.outputs.details_url }} --collect.isSinglePageApplication=true
        if: success()
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: lighthouse-front-production
          path: .lighthouseci
