name: Deployment

on:
  release:
    types:
      - created

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.setup.outputs.cache-key }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        id: setup
        uses: ./.github/actions/setup

  deploy_front:
    needs: setup
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.firebase.outputs.url }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          cache-key: ${{ needs.setup.outputs.cache-key }}
      - run: npx nx run front:build:production
      - name: Deploy front to hosting production
        uses: ./.github/actions/firebase/hosting
        if: success()
        id: firebase
        with:
          env: live
          name: front-production
          token: ${{ secrets.GITHUB_TOKEN }}
          project-id: ${{ secrets.FIREBASE_PROJECT_ID_PRODUCTION }}
          service-account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NX_MONO }}
          lhci-token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

  deploy_api:
    needs: setup
    runs-on: ubuntu-latest
    environment:
      name: api-production
      url: ${{ steps.firebase.outputs.url }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          cache-key: ${{ needs.setup.outputs.cache-key }}
      - run: npx nx run api:build:production
      - name: Deploy api to functions production
        uses: ./.github/actions/firebase/functions
        id: firebase
        if: success()
        with:
          project-name: api-production
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
          url: ${{ secrets.FIREBASE_PROJECT_PRODUCTION_API_URL }}
